name: Release

on:
  release:
    types:
      - created
  push:
    branches:
      - 'wheel/**'

jobs:
  build_Linux_wheels:
    name: Build manylinux
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python3-version: ['10']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up container
      run: |
        docker create --name linux_build -i -v /:/host quay.io/pypa/manylinux_2_28_x86_64:latest /bin/bash
        docker cp . linux_build:/tket/
    - name: Run build
      run: |
        docker start linux_build
        docker exec -e PY_TAG="cp3${{ matrix.python3-version }}-cp3${{ matrix.python3-version }}" -e CONAN_PROFILE=linux-x86_64-gcc12 linux_build /bin/bash -c "/tket/.github/workflows/linuxbuildwheel"
        mkdir wheelhouse
        docker cp linux_build:/tket/pytket/audited/. wheelhouse/
    - uses: actions/upload-artifact@v4
      with:
        name: Linux_3.${{ matrix.python3-version }}_wheel
        path: wheelhouse/
